theme = "shikama"

[editor]
scroll-lines = 1
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"

[keys.normal]
"C-c" = "normal_mode"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"esc" = "toggle_comments"

[keys.insert]
"C-c" = "normal_mode"
"A-a" = "code_action"
