theme = "shikama"

[editor]
scroll-lines = 1
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"

[keys.normal]
"C-c" = "normal_mode"
"esc" = "normal_mode"

# カーソル移動
"C-e" = "goto_line_end"
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_line_down"
"C-p" = "move_line_up"

[keys.insert]
"C-c" = "normal_mode"
"A-a" = "code_action"

# カーソル移動
"C-e" = "goto_line_end"
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_line_down"
"C-p" = "move_line_up"
