theme = "shikama"

[editor]
scroll-lines = 1
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"

[keys.normal]
";" = "toggle_comments"

"C-c" = "normal_mode"
"esc" = "normal_mode"

# コピペ
"C-l" = ["goto_line_start", "kill_to_line_end"]
"C-k" = ["extend_to_line_end", "yank", "delete_selection"]
"C-y" = "paste_before"

# カーソル移動
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_line_down"
"C-p" = "move_line_up"
# ページ単位で移動
"C-v" = "page_down"
"S-v" = "page_up"

[keys.insert]
"C-c" = "normal_mode"
"A-a" = "code_action"

# コピペ
"C-l" = ["goto_line_start", "kill_to_line_end"]
"C-k" = ["extend_to_line_end", "yank", "delete_selection"]
"C-y" = "paste_before"

# カーソル移動
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_line_down"
"C-p" = "move_line_up"
# ページ単位で移動
"C-v" = "page_down"
"S-v" = "page_up"

[keys.select]
"C-c" = "normal_mode"

# コメントアウト
";" = "toggle_comments"

# コピペ
"C-l" = ["goto_line_start", "kill_to_line_end"]
"C-k" = ["extend_to_line_end", "yank", "delete_selection"]
"C-y" = "paste_before"

# カーソル移動
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_line_down"
"C-p" = "move_line_up"