# Author: Shafkath Shuhan <shafkathshuhannyc@gmail.com>

"namespace" = { fg = "3f444a" }
"module" = { fg = "#5ad00" }

"type" = { fg = "#A6E22E" }
"type.builtin" = { fg = "#BAFF2E" }
"type.enum.variant" = { fg = "text" } 
"constructor" = { fg = "text" }
"variable.other.member" = { fg = "variable" }

"keyword" = { fg = "keyword" }
"keyword.directive" = { fg = "keyword" }
"keyword.control" = { fg = "keyword" }
"label" = { fg = "keyword" }

"special" = { fg = "keyword" }
"operator" = { fg = "text" }

"punctuation" = { fg = "text" }
"punctuation.delimiter" = { fg = "text" }

"variable" = { fg = "variable" }
"variable.parameter" = { fg = "#fd971f" }
"variable.builtin" = { fg = "#ff5FCF" }
"constant" = { fg = "F8F000" }
"constant.builtin" = { fg = "#ae81ff" }

"function" = { fg = "#fedd38" }
"function.builtin" = { fg = "fn_declaration" }
"function.macro" = { fg = "keyword" }
"attribute" = { fg = "fn_declaration" }

"comment" = { fg = "#78bd65" }

"string" = { fg = "#b978ab" }
"constant.character" = { fg = "#FF89ab" }
"string.regexp" = { fg = "regex" }
"constant.numeric" = { fg = "#aeAAff" }
"constant.character.escape" = { fg = "#ae81ff" }

"ui.background" = { fg = "text" }

"ui.window" = { bg = "widget" }
"ui.popup" = { bg = "widget" }
"ui.help" = { bg = "widget" }
"ui.menu.selected" = { bg = "widget" }

"ui.cursor" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "#888888", modifiers = ["reversed"] }

"ui.selection" = { bg = "#878b91" }
"ui.selection.primary" = { bg = "#575b61" }

"ui.linenr" = { fg = "#90908a" }
"ui.linenr.selected" = { fg = "#c2c2bf" }

"ui.statusline" = { fg = "active_text", bg = "#75715e" }
"ui.statusline.inactive" = { fg = "active_text", bg = "#75715e" }

"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "active_text" }

"warning" = { fg = "#cca700" }
"error" = { fg = "#f48771" }
"info" = { fg = "#75beff" }
"hint" = { fg = "#eeeeeeb3" }

diagnostic = { modifiers = ["underlined"] }

[palette]
type = "#A6E22E"
keyword = "#F92672"
regex = "#CE9178"
special = "#C586C0"
variable = "#4fb3d8"
fn_declaration = "#A6E22E"

background = "#272822"
text = "#f8f8f2"
active_text = "#ffffff"
cursor = "#a6a6a6"
inactive_cursor = "#878b91"
widget = "#1e1f1c"
